const SALES = 'SALES';
const SALES_REQ = 'SALES_REQ';

const SET_LOADER = 'SET_LOADER';
const CLEAR_LOADER = 'CLEAR_LOADER';

const FETCH_ERROR = 'FETCH_ERROR';
const CLEAR_FETCH_ERROR = 'CLEAR_FETCH_ERROR';

export {
    SALES,
    SALES_REQ,
    SET_LOADER,
    CLEAR_LOADER,
    FETCH_ERROR,
    CLEAR_FETCH_ERROR
}